name: "Run Calculator Tests"
on: push
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "check out code" 
              uses: actions/checkout@v3

            - name: "set up python"
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: "install dependencies"
              run: pip install -r requirements.txt

            - name: "install package"
              run: pip install -e .

            - name: "run pytest"
              run: python -m pytest tests/test_calculator.py -vs --html=test-report.html --self-contained-html

            - name: "save test results"
              uses: actions/upload-artifact@v4
              with:
                name: "test results"
                path: ./test-report.html

            - name: "display secret message"
              run: echo "The secret is ${{ secrets.MY_SECRET_MESSAGE }}"
    deploy:
        needs: test  
        runs-on: ubuntu-latest
        steps:
            - name: "check out code" 
              uses: actions/checkout@v3

            - name: "download test report"
              uses: actions/download-artifact@v4
              with:
                name: "test results"

            - name: "copy test report to docs"
              run: cp test-report.html docs/

            - name: "upload docs as an artifact"
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./docs

            - name: "publish to GitHub Pages"
              uses: actions/deploy-pages@v4
