name: "Run Calculator Tests"
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "check out code" 
              uses: actions/checkout@v3

            - name: "set up python"
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: "install dependencies"
              run: pip install -r requirements.txt

            - name: "run pytest"
              run: python -m pytest tests/test_calculator.py -vs
